---
title: "Getting started"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{reschola}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This document describes the basics of working with this package and provides signposting to more detailed documentation of setup and workflow used at Schola Empirica.

The most important components include:

### Guidance on how to set up your computer and your mind for doing data analysis the Schola way

See the [Setup](setup.html) vignette (`vignette('setup', package = 'reschola')`).

(If R cannot find the vignette, make sure you add `build_vignettes = TRUE` in `install_github("scholaempirica/reschola)`).

There are tips for setup in the [tips](tips.html) vignette.

### An Rstudio project template for easy project setup

This is accessed through the RStudio menu: File > New project > New directory > Standard Schola Empirica Project.

See the [Workflow](workflow.html) vignette for how to make the best use of the template in the context of the Schola Empirica workflow. (`vignette('workflow', package = 'reschola')`).

### Templates for producing reports in the Schola style

Accessed through the RStudio menu: `File > New File > R Markdown > From Template` > [scroll down to reschola package], or through `draft_*` functions in the reschola package.

See the [Workflow](workflow.html) vignette (`vignette('workflow', package = 'reschola')`) for details.

There are tips for working efficiently and for packages for specific tasks in the [tips](tips.html) vignette.

### A ggplot2 theme in the Schola style and related plotting utilities

See [Making charts [TODO]](charts.html) vignette (`vignette('charts', package = 'reschola')`) for details and related guidance and resources on making charts in `ggplot2`.

### Meta: keeping this packate up to date and up to scratch

This package should be a living, evolving tool and a set of living documents.
See the See [Developing this pacakge further](meta.html) vignette (`vignette('meta', package = 'reschola')`) to understand how this package is being developed and thus how it can be extended and updated.

You can get a list of these vignettes in R by entering `browseVignettes('reschola')` and view them locally if you wish
