
#' schola_project
#'
#' Function to parse inputs from New project dialog and create new project
#'
#' @param path path
#' @param ... other params from new project dialog, created in DCF file
#' @keywords internal
#' @return TRUE
schola_project <- function(path, ...) {
  # print(usethis::proj_sitrep())
  dots <- list(...)
  if(is.null(dots$title)) dots$title <- path
  if(is.null(dots$drive_folder)) dots$drive_folder <- ""

  # if drive folder given, check that it is a folder (not a file etc.)

  if(dots$drive_folder != "") {
    tryCatch(gdrive_dribble <- googledrive::as_dribble(dots$drive_folder),
             error = function(cnd) usethis::ui_oops("You need to authenticate R to your Google Drive account.
                                                    Run {usethis::ui_code('googledrive::drive_auth() after the project is created')}
                                                    then download the files from drive using {usethis::ui_code('reschola::gd_download_folder(gd_url)'})"))
    if(!googledrive::is_folder(gdrive_dribble)) {
      usethis::ui_stop("It seems the GDrive folder URL you have given does not point to a folder.")
    }
  }

  orig_dir <- usethis::proj_sitrep()[["active_rstudio_proj"]]

  # create directory and project

  usethis::create_project(path, open = FALSE)
  usethis::proj_set(path)
  setwd(path)
  # print("dir created")
  # print(usethis::proj_sitrep())

  # handle git(hub) setup

  # print("start switch")
  switch(dots[["vcs"]],
    none = usethis::ui_info("Not setting up any git version control."),
    "local git" = usethis::use_git(),
    "Github: private owned by me" = {
      # print("use_git")
      usethis::use_git()
      # print("use_github")
      usethis::use_github(private = T)
    },
    "Github: public owned by me" = {
      usethis::use_git()
      usethis::use_github()
    },
    "Github: public owned by scholaempirica" = {
      usethis::use_git()
      usethis::use_github(organisation = "scholaempirica")
    },
  )

  # text that will go into shared.R

  shared_code <- stringr::str_glue("
  # This file was generated by project setup to hold shared variables for project {dots$title}.
  # It is loaded by default by each RMarkdown file created using reschola's templates.
  # You should add all variables needed in multiple scripts here.\n
  # Do not add passwords, API keys and other information that should not be made public.\n
  # Store those in .Renviron. usethis::edit_r_environ() opens it for you for editing.
  project_title <- \"{dots$title}\"
  gd_url <- \"{dots$drive_folder}\"")

  writeLines(shared_code, con = "shared.R")

  # text that will go into build.R

  build_code <- c(stringr::str_glue(
  "# This file was generated by project setup for project {dots$title}."),
  "# As you work on the project, you should add commands to this file so that",
  "# it contains the commands needed to rebuild the whole project from scratch.",
  "# Typically, those will be source() or rmarkdown::render() calls, like below.\n\n",
  "source('00_read-data.R')",
  "source('000_check-and-transform-data.R')",
  "rmarkdown::render('01_schola-styled-word.Rmd', output_dir = 'reports-output')",
  "rmarkdown::render('02_schola-styled-redoc.Rmd', output_dir = 'reports-output')",
  "rmarkdown::render('99_reproducibility.Rmd', output_dir = 'reports-output')",
  sep = "\n\n")

  writeLines(build_code, con = "build.R")

  # Text that will go into README.md

  title_readme <- ifelse(dots$title == "", path, dots$title)

  readme_text <- c(stringr::str_glue("# {title_readme}\n\n\n"),
  "<!-- badges: start -->",
  "<!-- badges: end -->\n",
  "This is the README file for your project. Edit it as you like.\n",
  "It shows up when someone looks at the Github repository.\n",
  "It should inform others what the project is about and give basic",
  "information about what is in the repository and how to use it.\n\n",
  "If you would like to run R code in your README, run `usethis::use_readme_rmd()`",
  "\n\n",
  "This project was created using the `reschola` project template",
  "and should follow the `reschola` workflow.\n",
  "See <scholaemprica.github.io/reschola> for details.\n\n\n",
  "Note that the `data-raw` and `data-processed` directories are intentionally configured",
  "to disallow adding files to git, and hence empty on Github.",
  "The raw data is to be inserted manually or downloaded from Google Drive",
  "and the processed data is created by the scripts in the project.\n",
  "See the project documentation to see exactly how to recreate the data files.",
  "Only change the .gitignore files in those directories if you are sure it is a good idea.")

  writeLines(readme_text, con = "README.md")

  # Copy getting-started if option was checked

  if(dots$getting_started) {
    gs_rmd <- reschola_file(
      "rstudio", "templates", "project",
      "proj_fls", "getting-started.Rmd"
    )
    fs::file_copy(gs_rmd, "getting-started.Rmd")
  }

  # copy logos if option was checked

  if (dots[["copy_logos"]]) {
    logos <- reschola_file(
      "rstudio", "templates", "project",
      "proj_fls", "logos"
    )

    fs::dir_copy(logos, new_path = "logos")
  }

  gs_repro <- reschola_file(
    "rstudio", "templates", "project",
    "proj_fls", "99_reproducibility.Rmd"
  )
  fs::file_copy(gs_repro, "99_reproducibility.Rmd")

  gs_bookdown <- reschola_file(
    "rstudio", "templates", "project",
    "proj_fls", "_bookdown.yml"
  )
  fs::file_copy(gs_bookdown, "_bookdown.yml")

  # Create sample files

  # print(usethis::proj_sitrep())
  draft_word(name  = "01_schola-styled-word.Rmd", open = F)
  # draft_redoc(name = "02_schola-styled-redoc.Rmd", open = F)

  # delete R directory which was created automatically

  fs::dir_delete("R")

  # create the rest of the project structure

  fs::dir_create("data-input")
  usethis::use_git_ignore("*", "data-input") # have git ignore everything in that dir
  usethis::use_git_ignore("!.gitignore", "data-input") # except the .gitignore, so the dir will be committed
  fs::dir_create("data-processed")
  usethis::use_git_ignore("*", "data-processed") # ditto
  usethis::use_git_ignore("!.gitignore", "data-processed") #ditto
  fs::dir_create("data-output")
  fs::dir_create("charts-output")
  fs::dir_create("reports-output")

  # print("adding retrieve script")

  # add data retrieval script

  gs_retrieve_script <- reschola_file(
    "rstudio", "templates", "project",
    "proj_fls", "0_retrieve-data.R"
  )
  fs::file_copy(gs_retrieve_script, "001_retrieve-data.R")

  # print("Making dummy files")

  fs::file_create("002_read-data.R")
  fs::file_create("003_check-and-process-data.R")


  # print("adding GD files")
  if (dots[["drive_download"]] & (dots[["drive_folder"]] == "")) {
    usethis::ui_oops("You asked for the GDrive files to be downloaded, but provided no URL.
                     Not downloading anything.")
  }
  if (dots[["drive_download"]] & (dots[["drive_folder"]] != "")) {
    usethis::ui_todo("Downloading contents of GDrive to {usethis::ui_path('data-input')}")
    reschola::gd_download_folder(dots$drive_folder, overwrite = F, files_from_subfolders = T)
  }

  # usethis::ui_todo("You should run {usethis::ui_code('usethis::proj_set(getwd())')} in your original session to get your working directory sorted.")
  suppressMessages(usethis::proj_set(orig_dir))
  try(setwd(orig_dir), silent = T)
  return(TRUE)
}
