
#' schola_project
#'
#' Function to parse inputs from New project dialog and create new project
#'
#' @param path path
#' @param ... other params from new project dialog, created in DCF file
#' @keywords internal
#' @return TRUE
schola_project <- function(path, ...) {
  # print(usethis::proj_sitrep())
  dots <- list(...)
  if(is.null(dots$title)) dots$title <- path
  if(is.null(dots$drive_folder)) dots$drive_folder <- ""

  orig_dir <- usethis::proj_sitrep()[["active_rstudio_proj"]]

  # create directory and project

  usethis::create_project(path, open = FALSE)
  usethis::proj_set(path)
  setwd(path)
  # print("dir created")
  # print(usethis::proj_sitrep())

  # handle git(hub) setup

  # print("start switch")
  switch(dots[["vcs"]],
    none = usethis::ui_info("Not setting up any git version control."),
    "local git" = usethis::use_git(),
    "Github: private owned by me" = {
      # print("use_git")
      usethis::use_git()
      # print("use_github")
      usethis::use_github(private = T)
    },
    "Github: public owned by me" = {
      usethis::use_git()
      usethis::use_github()
    },
    "Github: public owned by scholaempirica" = {
      usethis::use_git()
      usethis::use_github(organisation = "scholaempirica")
    },
  )


  shared_code <- stringr::str_glue("
  # This file was generated by project setup to hold shared variables for project {dots$title}.
  # It is loaded by default by each RMarkdown file created using reschola's templates.
  # You should add all variables needed in multiple scripts here.\n
  # Do not add passwords, API keys and other information that should not be made public.\n
  # Store those in .Renviron. usethis::edit_r_environ() opens it for you for editing.
  project_title <- \"{dots$title}\"
  gd_url <- \"{dots$drive_folder}\"")

  writeLines(shared_code, con = "shared.R")

  build_code <- c(stringr::str_glue(
  "# This file was generated by project setup for project {dots$title}."),
  "# As you work on the project, you should add commands to this file so that",
  "# it contains the commands needed to rebuild the whole project from scratch.",
  "# Typically, those will be source() or rmarkdown::render() calls, like below.\n\n",
  "rmarkdown::render('01_schola-styled-Word.Rmd', output_dir = 'report-output')",
  "rmarkdown::render('02_schola-styled-redoc.Rmd', output_dir = 'report-output')",
  sep = "\n\n")

  writeLines(build_code, con = "build.R")

  readme_text <- c(stringr::str_glue("# {dots$title}\n\n\n"),
  "<!-- badges: start -->",
  "<!-- badges: end -->\n",
  "This is the README file for your project. Edit it as you like.\n",
  "It shows up when someone looks at the Github repository.\n",
  "It should inform others what the project is about and give basic",
  "information about what is in the repository and how to use it.\n\n",
  "If you would like to run R code in your README, run `usethis::use_readme_rmd()`")

  writeLines(readme_text, con = "README.md")

  if(dots$getting_started) {
    gs_rmd <- reschola_file(
      "rstudio", "templates", "project",
      "proj_fls", "getting-started.Rmd"
    )
    fs::file_copy(gs_rmd, "getting-started.Rmd")
  }

  if (dots[["copy_logos"]]) {
    logos <- reschola_file(
      "rstudio", "templates", "project",
      "proj_fls", "logos"
    )

    fs::dir_copy(logos, new_path = "logos")
  }


  # print(usethis::proj_sitrep())
  draft_word(name  = "01_schola-styled-Word.Rmd", open = F)
  draft_redoc(name = "02_schola-styled-redoc.Rmd", open = F)

  fs::dir_delete("R")
  fs::dir_create("data-input")
  fs::dir_create("data-processed")
  fs::dir_create("data-output")
  fs::dir_create("charts-output")
  fs::dir_create("reports-output")

  # print("adding retrieve script")

  gs_retrieve_script <- reschola_file(
    "rstudio", "templates", "project",
    "proj_fls", "0_retrieve-data.R"
  )
  fs::file_copy(gs_retrieve_script, "0_retrieve-data.R")

  # print("Making dummy files")

  fs::file_create("00_load-data.R")
  fs::file_create("000_check-and-process-data.R")


  # print("adding GD files")

  if (dots[["drive_download"]]) {
    usethis::ui_todo("Downloading contents of GDrive to {usethis::ui_path('data-input')}")
    reschola::gd_download_folder(dots$drive_folder, overwrite = F, files_from_subfolders = T)
  }

  # usethis::ui_todo("You should run {usethis::ui_code('usethis::proj_set(getwd())')} in your original session to get your working directory sorted.")
  suppressMessages(usethis::proj_set(orig_dir))
  try(setwd(orig_dir), silent = T)
  return(TRUE)
}
